### ISSUE TITLE
Problems subscribing to cov

### ISSUE THREAD

**Issue by Edu8030** [Bepacom-Raalte/Bepacom-BACnet-IP-Integration#13]
Hi there, i've tried to setup your addon to control a Regin controller but i'm getting the same error over and over and it doesn't matter if i use the dev version or any of the 3. Here  is a part of my log with the error. 
Strange thing is I am able to subscribe with yabe and everything is working normal. I feel like its something on the side of the Regin but i'm totally stuck for now. Hope you have an idea.

2024/02/07 23:04:18 [info] 338#338: *6 client 172.30.32.2 closed keepalive connection
ERROR:    Disconnected...

ERROR:    Error while subscribing to device,1006, analog-input,2: resources: no-space-to-add-list-element
ERROR:    Error while subscribing to device,1006, analog-input,2: resources: no-space-to-add-list-element
ERROR:    Error while subscribing to device,1006, analog-input,2: resources: no-space-to-add-list-element
ERROR:    Error while subscribing to device,1006, analog-input,2: resources: no-space-to-add-list-element
ERROR:    Error while subscribing to device,1006, analog-input,2: resources: no-space-to-add-list-element
ERROR:    Error while subscribing to device,1006, analog-input,2: resources: no-space-to-add-list-element
ERROR:    Error while subscribing to device,1006, analog-input,2: resources: no-space-to-add-list-element
2024/02/07 23:39:35 [info] 338#338: *14 client 172.30.32.2 closed keepalive connection
ERROR:    Error while subscribing to device,1006, analog-input,2: resources: no-space-to-add-list-element
ERROR:    Disconnected...

**Comment by Bepacom-Raalte** [comment]
Hello!

The error is caused because there seems to not enough dynamic memory in your device.

![afbeelding](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/126168314/1bc9408d-6d12-476b-8175-5eb5b62cba52)

This could be because the add-on is making a duplicate subscription of a previously made one. 
Could you make a screenshot of Yabe in which you show the device object's Active Cov Subscriptions (if it has this property)?

In Yabe, is the subscription Cov or Poll? 

![afbeelding](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/126168314/51e86c95-834a-4c18-a32c-55c49ac0e2db)

I've encountered this error once with a Siemens controller, and restarting it helped resolve it. Maybe this can help you as well.
If this is a limitation with the Regin controller, could you maybe give me type for the controller? Maybe there's some documentation that can help me figure out why it's giving this error.

**Comment by Edu8030** [comment]
Thanks for the quick reply!
Looks like its working finally, and you were right about which way to think. 
The max COV subscription limit is 0 by default. So i've found the BACNET adress to write a different value to. Its very deep inside the program (i've just started with this controller so i had no idea where to look)
When finished loading the software it is very important to do a reboot(just disconnect) the power as it seems)
Now i'm going to add some more bacnet objects and see if it will continue working.
Thanks again great work!
![2024-02-08 193715](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/159388861/d4ef83c3-069d-4826-9e81-f1b8b19e15c9)

**Comment by Bepacom-Raalte** [comment]
Glad it's working! Let me know if there's any more issues.
Feel free to reopen this issue or start a new one if you encounter any.

**Comment by Edu8030** [comment]
Well I’ve bumped into another thing.
I’m trying to send co2 over bacnet to the controller but from HA I can’t send values over 100… is there a possibility to set this up somewhere?

**Comment by Bepacom-Raalte** [comment]
The integration checks if the object has a Min or Max_Pres_Value property available, and if it doesn't exist it will limit the values to +100 and -100.
If you're comfortable adjusting the integration code, you could change the classes in the number.py file to the following:

![afbeelding](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/126168314/c5fe8afb-37fb-4374-bf0b-2cea305179cd)

Otherwise, I'd recommend adding these properties.

**Comment by Edu8030** [comment]
Hi,
I did change the code for the integration but it seems not to have any affect. It’s still -100 to 100
Now have divided the value by 100 and in the controller I’ve set it back.

**Comment by GravySeal** [comment]
In the next update I'll make sure the limit is higher so there's no scaling necessary.

**Comment by Edu8030** [comment]
That would be great. For now I will be testing but it looks very stable.
